{{ if .Values.openWebUI.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: open-web-ui 
  namespace: flux-system
spec:
  interval: 600m
  url: https://helm.openwebui.com/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-web-ui-hr 
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 5m
  chart:
    spec:
      chart: open-webui
      sourceRef:
        kind: HelmRepository
        name: open-web-ui
        namespace: flux-system
  values: 	
    {{ .Values.openWebUI.values | toYaml | nindent 4 }}
{{- end }}