apiVersion: v2
appVersion: v0.107.7
description: DNS proxy as ad-blocker for local network
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/adguard-home
icon: https://avatars3.githubusercontent.com/u/8361145?s=200&v=4?sanitize=true
keywords:
- adguard-home
- adblock
- dns
kubeVersion: '>=1.16.0-0'
name: adguard-home
sources:
- https://github.com/AdguardTeam/AdGuardHome
version: 5.5.2
